@startuml Dss pour le scénario Redémarrer
title Dss pour le scénario Redémarrer
hide footbox
skinparam style strictuml
skinparam packageStyle rect
skinparam backgroundcolor transparent
skinparam defaultfontname Verdana
actor ":Joueur" as J
participant ":Système" as S
J -> S : redémarrerJeu()
@enduml
